"""Offline analysis fallback — pattern-matching used when no AI engine is available."""

import os
import re


def heuristic_analyze(content: str, filename: str, language: str) -> dict:
    """Build a best-effort analysis dict purely from regex pattern matching."""
    title = os.path.splitext(filename)[0]
    title = re.sub(r'^\d+[_\-\s]*', '', title)  # Strip leading numbers
    title = re.sub(r'[_\-]+', ' ', title).strip().title()

    tags = _detect_tags(content)
    lines = len(content.strip().split('\n'))
    difficulty = 'Easy' if lines < 30 else 'Medium' if lines < 80 else 'Hard'
    approaches = _extract_approaches(content, language)

    deep_analysis = {
        "overall_summary": (
            f"Heuristic analysis of {filename}. {len(approaches)} approach(es) detected. "
            f"For a full AI-powered deep analysis with line-by-line breakdown, ensure your "
            f"GROQ_API_KEY is set in the .env file and rebuild the Docker container."
        ),
        "approaches": [
            {
                "approach_name": a["approach_name"],
                "summary": a["explanation"] or f"Approach: {a['approach_name']}",
                "time_complexity": a.get("time_complexity", ""),
                "space_complexity": a.get("space_complexity", ""),
                "line_breakdown": [],
            }
            for a in approaches
        ],
        "key_insights": [
            "⚠️ This analysis was generated by heuristic pattern matching (no AI).",
            "Set GROQ_API_KEY in your .env file and rebuild Docker for AI analysis.",
        ],
        "common_mistakes": [],
    }

    return {
        'title': title,
        'problem_statement': f'# {title}\n\n*Heuristic analysis — upload with AI key for detailed description.*\n\nSolution file: `{filename}`',
        'difficulty': difficulty,
        'dsa_tags': tags[:5],
        'extracted_approaches': approaches,
        'generated_test_cases': [],
        'deep_analysis': deep_analysis,
    }


_TAG_PATTERNS = {
    'DP': [r'dp\[', r'memo\[', r'tabulation', r'memoiz'],
    'Array': [r'arr\[', r'nums\[', r'vector<'],
    'String': [r'string\s', r'str\[', r'substr'],
    'Tree': [r'TreeNode', r'root\->', r'left.*right'],
    'Graph': [r'adj\[', r'graph\[', r'BFS|DFS', r'visited'],
    'Stack': [r'stack<', r'\.push\(', r'\.pop\('],
    'Queue': [r'queue<', r'deque'],
    'Binary Search': [r'binary.?search', r'low.*high.*mid', r'left.*right.*mid'],
    'Greedy': [r'greedy', r'sort\('],
    'Recursion': [r'return\s+\w+\(', r'recursive'],
    'Linked List': [r'ListNode', r'next\s*=', r'head\->'],
    'Hash Map': [r'unordered_map', r'HashMap', r'dict\(', r'\{\}'],
    'Two Pointers': [r'left.*right', r'i.*j.*while'],
    'Sorting': [r'sort\(', r'sorted\(', r'Arrays\.sort'],
    'Backtracking': [r'backtrack', r'permut', r'combinat'],
    'Sliding Window': [r'window', r'sliding'],
    'Heap': [r'priority_queue', r'heapq', r'PriorityQueue'],
}


def _detect_tags(content: str) -> list:
    tags = []
    for tag, pats in _TAG_PATTERNS.items():
        for pat in pats:
            if re.search(pat, content, re.IGNORECASE):
                tags.append(tag)
                break
    return tags if tags else ['General']


def _extract_approaches(content: str, language: str) -> list:
    """Extract multiple approaches from commented/labelled blocks in a file."""
    approaches = []

    if language in ('cpp', 'java', 'c'):
        blocks = re.split(
            r'(?:^|\n)\s*(?://|/\*)\s*(?:Approach|Method|Solution|Way)\s*\d*\s*[:\-]?\s*',
            content, flags=re.IGNORECASE,
        )
    elif language == 'python':
        blocks = re.split(
            r'(?:^|\n)\s*#\s*(?:Approach|Method|Solution|Way)\s*\d*\s*[:\-]?\s*',
            content, flags=re.IGNORECASE,
        )
    else:
        blocks = [content]

    if len(blocks) <= 1:
        blocks = re.split(r'\n\s*(?://\s*[-=]{5,}|#\s*[-=]{5,}|/\*\s*[-=]{5,})', content)

    if len(blocks) <= 1:
        commented = _extract_commented_code(content, language)
        if commented:
            approaches.append({
                'approach_name': 'Active Solution',
                'raw_code': _strip_comments_from_active(content, language),
                'time_complexity': _guess_complexity(content),
                'space_complexity': '',
                'explanation': 'The currently active (uncommented) solution.',
            })
            for i, block in enumerate(commented):
                approaches.append({
                    'approach_name': f'Alternative Approach {i + 1}',
                    'raw_code': block,
                    'time_complexity': '',
                    'space_complexity': '',
                    'explanation': 'Commented-out alternative solution.',
                })
        else:
            approaches.append({
                'approach_name': 'Original Solution',
                'raw_code': content.strip(),
                'time_complexity': _guess_complexity(content),
                'space_complexity': '',
                'explanation': 'Complete solution as uploaded.',
            })
    else:
        for i, block in enumerate(blocks):
            block = block.strip()
            if not block or len(block) < 10:
                continue
            first_line = block.split('\n')[0].strip()
            name = re.sub(r'^[/#\*\s]+', '', first_line).strip()
            name = name if name and len(name) < 80 else f'Approach {i}'
            approaches.append({
                'approach_name': name,
                'raw_code': block,
                'time_complexity': _guess_complexity(block),
                'space_complexity': '',
                'explanation': '',
            })

    return approaches


def _extract_commented_code(content: str, language: str) -> list:
    """Extract large blocks of commented-out code (>3 lines)."""
    blocks = []
    current_block = []
    for line in content.split('\n'):
        stripped = line.strip()
        is_comment = False
        if language in ('cpp', 'java', 'c'):
            is_comment = stripped.startswith('//')
        elif language == 'python':
            is_comment = stripped.startswith('#')
        if is_comment:
            if language in ('cpp', 'java', 'c'):
                current_block.append(re.sub(r'^//\s?', '', stripped))
            else:
                current_block.append(re.sub(r'^#\s?', '', stripped))
        else:
            if len(current_block) >= 3:
                code = '\n'.join(current_block)
                if re.search(r'[{(;=]|def |class |return |if |for |while ', code):
                    blocks.append(code)
            current_block = []
    if len(current_block) >= 3:
        code = '\n'.join(current_block)
        if re.search(r'[{(;=]|def |class |return |if |for |while ', code):
            blocks.append(code)
    return blocks


def _strip_comments_from_active(content: str, language: str) -> str:
    lines = []
    for line in content.split('\n'):
        stripped = line.strip()
        if language in ('cpp', 'java', 'c') and stripped.startswith('//'):
            continue
        if language == 'python' and stripped.startswith('#'):
            continue
        lines.append(line)
    return '\n'.join(lines).strip()


def _guess_complexity(code: str) -> str:
    nested_loops = len(re.findall(r'for\s*\(|for\s+\w+\s+in|while\s*\(', code))
    if nested_loops >= 3:
        return 'O(n³)'
    if nested_loops >= 2:
        return 'O(n²)'
    if re.search(r'binary.?search|low.*high.*mid', code, re.IGNORECASE):
        return 'O(log n)'
    if re.search(r'sort\(|sorted\(', code):
        return 'O(n log n)'
    if nested_loops >= 1:
        return 'O(n)'
    return ''
